name: ci
on: [pull_request, push]
env:
  GOPRIVATE: github.com/sylabs/compute-service

jobs:
  build-and-unit-test:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        go: ['1.13.x']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Install go-bindata
        run: go get -u github.com/jteeuwen/go-bindata/...
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate
        run: go generate ./...
      - name: Build
        run: go build ./...
      - name: Unit Test
        run: go test -cover -race ./...
