name: ci
on:
  pull_request:
  push:
    branches:
      - master
env:
  GOPRIVATE: github.com/sylabs/fuzzball-service

jobs:
  lint-and-test-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-helm@v1
        with:
          version: v3.1.1
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint
        run: helm lint deployments/helm/fuzzball/

  build-and-unit-test:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        go: ['1.13.x','1.14.x']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Add Go Bin to Path
        run: echo "::add-path::$(go env GOPATH)/bin"
      - name: Install go-bindata
        run: go get -u github.com/go-bindata/go-bindata/...
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate
        run: go generate ./...
      - name: Build
        run: go build ./...
      - name: Unit Test
        run: go test -cover -race ./...

  integration-test:
    strategy:
      matrix:
        go: ['1.13.x','1.14.x']
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
      nats:
        image: nats
        ports:
          - 4222:4222
      redis:
        image: redis
        ports:
          - 6379:6379
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Add Go Bin to Path
        run: echo "::add-path::$(go env GOPATH)/bin"
      - name: Install go-bindata
        run: go get -u github.com/go-bindata/go-bindata/...
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate
        run: go generate ./...
      - name: Test
        run: go test -cover -race -tags=integration ./...
